# Pin the base image by digest for reproducible builds (tag: python:3.12-slim).
FROM python:3.12-slim@sha256:d764629ce0ddd8c71fd371e9901efb324a95789d2315a47db7e4d27e78f1b0e9

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install the hash-pinned production dependencies first (reproducible builds;
# supply-chain tampering fails the install). requirements.lock is prod-only
# (generated by `make lock`); the dev/test toolchain lives in requirements-dev.lock
# and is installed only in CI, never in the image.
COPY requirements.lock .
RUN pip install --require-hashes --no-cache-dir -r requirements.lock

# Copy application code (the repo .dockerignore keeps .env*/secrets/tests out of the build context)
COPY . .

# Install the local package only — deps are already pinned above, so --no-deps
# keeps the resolver from re-touching (and un-pinning) the dependency tree.
RUN pip install --no-deps --no-cache-dir .

# Run as an unprivileged user (least privilege; shrinks RCE/SSRF blast radius).
# uvicorn binds 8080 (>1024), so no root is required at runtime.
# Discovery cache dir (mounted on a docker volume in prod). Created before the
# chown so a named volume mounted here inherits appuser ownership on first use
# and the unprivileged runtime user can write the SQLite store.
RUN mkdir -p /app/.cache/discovery
RUN useradd --create-home --uid 10001 appuser \
    && chown -R appuser:appuser /app
USER appuser

EXPOSE 8080

# Liveness probe on the existing health route.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD curl -fsS http://localhost:8080/api/v1/health || exit 1

CMD ["uvicorn", "api.app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8080"]
